title: Fumi Inaba
email: [finaba@bccrc.com]
description: >- 
  Personal website and research portfolio.
baseurl: ""
url: "https://yourusername.github.io"
github_username: fuminaba

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2

nav_pages:
  - title: Home
    url: /
  - title: Research
    url: /research/
  - title: News
    url: /news/
  - title: Publications
    url: /publications/
  # - title: Blog
  #   url: /blog

# Pagination V2 settings
pagination:
  enabled: true
  per_page: 5 # Or your desired number of posts per page
  permalink: '/page/:num/' # How subsequent pages will be linked
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  # Optional: Configure for specific collections or pages
  # collection: 'posts' # Default is posts
  # Settings for the 'news' page
  autopages:
    enabled: true
    collections: # You might not need this if 'posts' is your news
      posts:
        enabled: true
        permalink: '/news/page/:num/' # Permalink for news pagination
        slugify:
          mode: 'pretty'
        title: 'News - Page :num' # Title for paginated news pages
        layouts: 
          - 'news_paginated.html' # A new layout file for the news listing
        # Required if you want your /news/index.html to be the first page
        # and then /news/page/2/, /news/page/3/ etc.