title: Fumi Inaba
email: "fumiy@student.ubc.ca"
description: >- 
  Personal website and research portfolio.
baseurl: ""
url: "https://fuminaba.github.io"
github_username: fuminaba

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  # jekyll-paginate-v2 has been removed!

nav_pages:
  - title: Home
    url: /
  - title: Research/Projects
    url: /research/
  - title: Publications
    url: /publications/
  - title: News
    url: /news/
  - title: Wiki
    url: /wiki/

collections:
  services:
    output: true
    permalink: /services/:title.html
  wiki: 
    output: true 
    permalink: /wiki/:year/:month/:day/:title.html
