title: Fumi Inaba
email: [fumiy@student.ubc.ca]
description: >- 
  Personal website and research portfolio.
baseurl: ""
url: "https://yourusername.github.io"
github_username: fuminaba

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2

nav_pages:
  - title: Home
    url: /
  - title: Research
    url: /research/
  - title: Publications
    url: /publications/
  - title: News
    url: /news/

# Pagination V2 settings
# In your _config.yml
# ... (other settings) ...

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/' # Global pagination permalink (can be overridden)
  title: ':title - page :num'
  # limit: 0
  sort_field: 'date'
  sort_reverse: true

  autopages:
    enabled: true
    collections:
      posts:
        enabled: true
        # This tells autopages to use the 'news_paginated.html' layout
        layouts:
          - 'news_paginated.html'
        # This is the permalink for pages 2, 3, etc.
        # The plugin will infer the base for page 1 from this.
        permalink: '/news/page/:num/'
        # Title for pages 2, 3, etc.
        title: 'News - Page :num'
        # Title for the first page (e.g., /news/)
        first_page_title: 'News' # Important for the generated /news/index.html
        # This ensures that the generated files are actually written to the _site directory
        output: true 
        # This section helps control the path for the first page if needed,
        # often it's inferred correctly but being explicit can help.
        # The `slugify` mode 'pretty' usually results in /collection_name/
        # so for 'posts' it might default to /posts/ if not overridden.
        # Since your permalink for subsequent pages is /news/page/:num/,
        # it *should* try to make the first page /news/
        # Let's ensure the slug for the 'posts' collection when autopaged is treated as 'news'
        # This might not be strictly necessary if permalink above is clear, but can help guide it.
        # slugify:
        #   mode: 'pretty' 
        #   collection_field: 'title' # or some other field if you want to base slug on collection metadata
        #   collection_slugs:
        #     posts: 'news' # This tells it to treat the 'posts' collection as if its base slug is 'news' for autopaging.
                           # This is more advanced and might not be needed. The permalink pattern usually dictates it.